# Generated by Django 6.0.3 on 2026-03-31 17:27

import django.db.models.deletion
import sleep.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepStudyPreference',
            fields=[
                ('preference_id', models.CharField(default=sleep.models.generate_preference_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('sleep_start', models.TimeField()),
                ('sleep_end', models.TimeField()),
                ('active_study_start', models.TimeField()),
                ('active_study_end', models.TimeField()),
                ('max_focus_hours', models.FloatField(default=6.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
