# Generated by Django 6.0.3 on 2026-03-31 17:27

import django.db.models.deletion
import schedule.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('session_id', models.CharField(default=schedule.models.generate_session_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField()),
                ('scheduled_hours', models.FloatField()),
                ('cls_contribution', models.FloatField(default=0.0)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_missed', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
