# Generated by Django 6.0.3 on 2026-03-31 17:27

import django.db.models.deletion
import tasks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.CharField(default=tasks.models.generate_task_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=20)),
                ('assignment_title', models.CharField(max_length=200)),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')])),
                ('estimated_hours', models.FloatField()),
                ('deadline', models.DateField()),
                ('cls_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(default='Low', max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
