# Generated by Django 6.0.3 on 2026-03-31 17:27

import django.db.models.deletion
import stress.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStressLog',
            fields=[
                ('log_id', models.CharField(default=stress.models.generate_log_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_cls', models.FloatField(default=0.0)),
                ('cls_percentage', models.FloatField(default=0.0)),
                ('stress_level', models.CharField(default='Low', max_length=10)),
                ('has_recommendation', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('recommendation_id', models.CharField(default=stress.models.generate_recommendation_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('overloaded_date', models.DateField()),
                ('suggested_date', models.DateField()),
                ('stress_reduction', models.FloatField(default=0.0)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Ignored', 'Ignored')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.studysession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
